from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import pandas as pd


@dataclass(frozen=True)
class VoltageAnomalyDataset:
    node_timeseries: pd.DataFrame
    labels: pd.DataFrame


def load_ieee14_voltage_anomaly_dataset(dataset_dir: Path) -> VoltageAnomalyDataset:
    """
    Load the minimal dataset generated by dt-dataset-factory.
    """
    node_csv = dataset_dir / "node_timeseries.csv"
    labels_csv = dataset_dir / "labels.csv"
    if not node_csv.exists() or not labels_csv.exists():
        raise FileNotFoundError(f"Expected {node_csv} and {labels_csv}")
    return VoltageAnomalyDataset(
        node_timeseries=pd.read_csv(node_csv),
        labels=pd.read_csv(labels_csv),
    )


def maybe_load_parquet(dataset_dir: Path) -> Optional[VoltageAnomalyDataset]:
    node_pq = dataset_dir / "node_timeseries.parquet"
    labels_pq = dataset_dir / "labels.parquet"
    if node_pq.exists() and labels_pq.exists():
        return VoltageAnomalyDataset(
            node_timeseries=pd.read_parquet(node_pq),
            labels=pd.read_parquet(labels_pq),
        )
    return None

